name: sepsis-sentinel
channels:
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.13
  - pytorch=2.1.*
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - pytorch-lightning=2.1.*
  - pytorch-geometric=2.4.*
  - pyg=2.4.*
  - pyspark=3.5.*
  - pandas=2.*
  - numpy=1.24.*
  - scikit-learn=1.3.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - plotly=5.17.*
  - pip
  - pip:
    - -r requirements.txt
